# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/robertcassidy/CIS565/Project3-Pathtracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/robertcassidy/CIS565/Project3-Pathtracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robertcassidy/CIS565/Project3-Pathtracer/CMakeFiles /Users/robertcassidy/CIS565/Project3-Pathtracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robertcassidy/CIS565/Project3-Pathtracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project3-Pathtracer

# Build rule for target.
Project3-Pathtracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project3-Pathtracer
.PHONY : Project3-Pathtracer

# fast build rule for target.
Project3-Pathtracer/fast:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/build
.PHONY : Project3-Pathtracer/fast

external/src/glslUtil/glslUtility.o: external/src/glslUtil/glslUtility.cpp.o
.PHONY : external/src/glslUtil/glslUtility.o

# target to build an object file
external/src/glslUtil/glslUtility.cpp.o:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/glslUtil/glslUtility.cpp.o
.PHONY : external/src/glslUtil/glslUtility.cpp.o

external/src/glslUtil/glslUtility.i: external/src/glslUtil/glslUtility.cpp.i
.PHONY : external/src/glslUtil/glslUtility.i

# target to preprocess a source file
external/src/glslUtil/glslUtility.cpp.i:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/glslUtil/glslUtility.cpp.i
.PHONY : external/src/glslUtil/glslUtility.cpp.i

external/src/glslUtil/glslUtility.s: external/src/glslUtil/glslUtility.cpp.s
.PHONY : external/src/glslUtil/glslUtility.s

# target to generate assembly for a file
external/src/glslUtil/glslUtility.cpp.s:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/glslUtil/glslUtility.cpp.s
.PHONY : external/src/glslUtil/glslUtility.cpp.s

external/src/stb_image/stb_image.o: external/src/stb_image/stb_image.c.o
.PHONY : external/src/stb_image/stb_image.o

# target to build an object file
external/src/stb_image/stb_image.c.o:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/stb_image/stb_image.c.o
.PHONY : external/src/stb_image/stb_image.c.o

external/src/stb_image/stb_image.i: external/src/stb_image/stb_image.c.i
.PHONY : external/src/stb_image/stb_image.i

# target to preprocess a source file
external/src/stb_image/stb_image.c.i:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/stb_image/stb_image.c.i
.PHONY : external/src/stb_image/stb_image.c.i

external/src/stb_image/stb_image.s: external/src/stb_image/stb_image.c.s
.PHONY : external/src/stb_image/stb_image.s

# target to generate assembly for a file
external/src/stb_image/stb_image.c.s:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/stb_image/stb_image.c.s
.PHONY : external/src/stb_image/stb_image.c.s

external/src/stb_image/stb_image_write.o: external/src/stb_image/stb_image_write.c.o
.PHONY : external/src/stb_image/stb_image_write.o

# target to build an object file
external/src/stb_image/stb_image_write.c.o:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/stb_image/stb_image_write.c.o
.PHONY : external/src/stb_image/stb_image_write.c.o

external/src/stb_image/stb_image_write.i: external/src/stb_image/stb_image_write.c.i
.PHONY : external/src/stb_image/stb_image_write.i

# target to preprocess a source file
external/src/stb_image/stb_image_write.c.i:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/stb_image/stb_image_write.c.i
.PHONY : external/src/stb_image/stb_image_write.c.i

external/src/stb_image/stb_image_write.s: external/src/stb_image/stb_image_write.c.s
.PHONY : external/src/stb_image/stb_image_write.s

# target to generate assembly for a file
external/src/stb_image/stb_image_write.c.s:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/external/src/stb_image/stb_image_write.c.s
.PHONY : external/src/stb_image/stb_image_write.c.s

src/image.o: src/image.cpp.o
.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i
.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s
.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scene.o: src/scene.cpp.o
.PHONY : src/scene.o

# target to build an object file
src/scene.cpp.o:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/scene.cpp.o
.PHONY : src/scene.cpp.o

src/scene.i: src/scene.cpp.i
.PHONY : src/scene.i

# target to preprocess a source file
src/scene.cpp.i:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/scene.cpp.i
.PHONY : src/scene.cpp.i

src/scene.s: src/scene.cpp.s
.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.cpp.s:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/scene.cpp.s
.PHONY : src/scene.cpp.s

src/utilities.o: src/utilities.cpp.o
.PHONY : src/utilities.o

# target to build an object file
src/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/utilities.cpp.o
.PHONY : src/utilities.cpp.o

src/utilities.i: src/utilities.cpp.i
.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/utilities.cpp.i
.PHONY : src/utilities.cpp.i

src/utilities.s: src/utilities.cpp.s
.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/Project3-Pathtracer.dir/build.make CMakeFiles/Project3-Pathtracer.dir/src/utilities.cpp.s
.PHONY : src/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Project3-Pathtracer"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... external/src/glslUtil/glslUtility.o"
	@echo "... external/src/glslUtil/glslUtility.i"
	@echo "... external/src/glslUtil/glslUtility.s"
	@echo "... external/src/stb_image/stb_image.o"
	@echo "... external/src/stb_image/stb_image.i"
	@echo "... external/src/stb_image/stb_image.s"
	@echo "... external/src/stb_image/stb_image_write.o"
	@echo "... external/src/stb_image/stb_image_write.i"
	@echo "... external/src/stb_image/stb_image_write.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

